name: Ubuntu

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        gcc:
          - "10"
          - "11"
          - "12"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        env:
          CC: gcc-${{ matrix.gcc }}
          CXX: g++-${{ matrix.gcc }}
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE:STRING=Debug
      - name: Build
        run: cmake --build build --config Debug
      - name: Test
        working-directory: build
        run: ctest --build-config Debug --output-on-failure
